### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by ebirn** [endrebak/goverlap#1]
For installing this software it would be great if you could tag your versions/releases in git, so that users and their support teams that are installing the software can reference a version number rather than a commit id.

**Comment by endrebak** [comment]
Completely agree.

I was putting it off til later since this is software that does not earn me cites and I did not want to spend too much time on it, but I think it will help me preserve my time (and sanity) in the end too.  From now on (any subsequent releases) I'll give my software version tags both in the code, cli and on git.
